class AdminDashboardData {
  int totalAssociations;
  int approvedAssociations;
  int pendingAssociations;
  int rejectedAssociations;
  int approvedAssociationsPercentage;
  int pendingAssociationsPercentage;
  int rejectedAssociationsPercentage;
  int totalRequests;
  int approvedRequests;
  int pendingRequests;
  int returnedRequests;
  int rejectedRequests;
  int approvedRequestsPercentage;
  int pendingRequestsPercentage;
  int returnedRequestsPercentage;
  int rejectedRequestsPercentage;
  int totalCompanies;
  int approvedCompanies;
  int pendingCompanies;
  int rejectedCompanies;
  int approvedCompaniesPercentage;
  int pendingCompaniesPercentage;
  int rejectedCompaniesPercentage;
  int totalProjects;
  int completedProjects;
  int completedProjectsByDonation;
  int activeProjects;
  int inactiveProjects;
  int completedProjectsPercentage;
  int completedProjectsByDonationPercentage;
  int activeProjectsPercentage;
  int inactiveProjectsPercentage;
  int totalEmployees;
  int activeEmployees;
  int inactiveEmployees;
  int activeEmployeesPercentage;
  int inactiveEmployeesPercentage;

  AdminDashboardData({
    required this.totalAssociations,
    required this.approvedAssociations,
    required this.pendingAssociations,
    required this.rejectedAssociations,
    required this.approvedAssociationsPercentage,
    required this.pendingAssociationsPercentage,
    required this.rejectedAssociationsPercentage,
    required this.totalRequests,
    required this.approvedRequests,
    required this.pendingRequests,
    required this.returnedRequests,
    required this.rejectedRequests,
    required this.approvedRequestsPercentage,
    required this.pendingRequestsPercentage,
    required this.returnedRequestsPercentage,
    required this.rejectedRequestsPercentage,
    required this.totalCompanies,
    required this.approvedCompanies,
    required this.pendingCompanies,
    required this.rejectedCompanies,
    required this.approvedCompaniesPercentage,
    required this.pendingCompaniesPercentage,
    required this.rejectedCompaniesPercentage,
    required this.totalProjects,
    required this.completedProjects,
    required this.completedProjectsByDonation,
    required this.activeProjects,
    required this.inactiveProjects,
    required this.completedProjectsPercentage,
    required this.completedProjectsByDonationPercentage,
    required this.activeProjectsPercentage,
    required this.inactiveProjectsPercentage,
    required this.totalEmployees,
    required this.activeEmployees,
    required this.inactiveEmployees,
    required this.activeEmployeesPercentage,
    required this.inactiveEmployeesPercentage,
  });

  factory AdminDashboardData.fromJson(Map<String, dynamic> json) => AdminDashboardData(
    totalAssociations: json["totalAssociations"],
    approvedAssociations: json["approvedAssociations"],
    pendingAssociations: json["pendingAssociations"],
    rejectedAssociations: json["rejectedAssociations"],
    approvedAssociationsPercentage: json["approvedAssociationsPercentage"],
    pendingAssociationsPercentage: json["pendingAssociationsPercentage"],
    rejectedAssociationsPercentage: json["rejectedAssociationsPercentage"],
    totalRequests: json["totalRequests"],
    approvedRequests: json["approvedRequests"],
    pendingRequests: json["pendingRequests"],
    returnedRequests: json["returnedRequests"],
    rejectedRequests: json["rejectedRequests"],
    approvedRequestsPercentage: json["approvedRequestsPercentage"],
    pendingRequestsPercentage: json["pendingRequestsPercentage"],
    returnedRequestsPercentage: json["returnedRequestsPercentage"],
    rejectedRequestsPercentage: json["rejectedRequestsPercentage"],
    totalCompanies: json["totalCompanies"],
    approvedCompanies: json["approvedCompanies"],
    pendingCompanies: json["pendingCompanies"],
    rejectedCompanies: json["rejectedCompanies"],
    approvedCompaniesPercentage: json["approvedCompaniesPercentage"],
    pendingCompaniesPercentage: json["pendingCompaniesPercentage"],
    rejectedCompaniesPercentage: json["rejectedCompaniesPercentage"],
    totalProjects: json["totalProjects"],
    completedProjects: json["completedProjects"],
    completedProjectsByDonation: json["completedProjectsByDonation"],
    activeProjects: json["activeProjects"],
    inactiveProjects: json["inactiveProjects"],
    completedProjectsPercentage: json["completedProjectsPercentage"],
    completedProjectsByDonationPercentage: json["completedProjectsByDonationPercentage"],
    activeProjectsPercentage: json["activeProjectsPercentage"],
    inactiveProjectsPercentage: json["inactiveProjectsPercentage"],
    totalEmployees: json["totalEmployees"],
    activeEmployees: json["activeEmployees"],
    inactiveEmployees: json["inactiveEmployees"],
    activeEmployeesPercentage: json["activeEmployeesPercentage"],
    inactiveEmployeesPercentage: json["inactiveEmployeesPercentage"],
  );


}
